
# Updated & Created by WarStylez

command /clearchat:
    description: Clear chat for all players ( by sending "" 300 times - Can be changed for longer chats or plugins ) 
    permission: chatclear.clear
    trigger:
        loop 300 times:
            broadcast " "
        broadcast "&6&m-----------------------------------------"
        broadcast "&b&l&cChat has been cleared by &6%player%!"
        broadcast "&6&m-----------------------------------------"
